export enum FavoriteLocationByUserActionTypes {
    GET_FAVORITE_LOCATION_BY_USER = '[Favorite_Location] GET_FAVORITE_LOCATION_BY_USER',
    GET_FAVORITE_LOCATION_BY_USER_SUCCESS = '[Favorite_Location] GET_FAVORITE_LOCATION_BY_USER_SUCCESS',
    GET_FAVORITE_LOCATION_BY_USER_FAIL = '[Favorite_Location] GET_FAVORITE_LOCATION_BY_USER_FAIL',
}